const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STORE='sigad_devoluciones_v01',AUDIT='sigad_auditoria_v01';
const titles={dashboard:['Dashboard','Sistema Integral de Gestión del Archivo Desconcentrado'],devoluciones:['Devolución de cargos','Generación y registro de oficios'],archivo360:['Archivo 360','Mapa inteligente de repositorios'],transferencias:['Transferencias','Transferencias documentales al Gobierno Regional'],eliminacion:['Eliminación documental','Registro estadístico de jornadas y procesos'],reportes:['Reportes','Informes consolidados de gestión'],auditoria:['Auditoría','Trazabilidad de operaciones'],asistente:['Asistente SIGAD','Consultas sobre la información registrada']};
const obsTypes=['FALTA RESOLUCIÓN DE ARCHIVO','NO ESTÁ EN LISTADO','EXPEDIENTE DUPLICADO','RESOLUCIÓN NO CORRESPONDE','FALTA TOMO','FOLIATURA / TOMOS','OTRO'];
let currentId=null;
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function isoToday(){return new Date().toISOString().slice(0,10)}
function fmtDate(v){if(!v)return'';const [y,m,d]=v.split('-');return `${d}/${m}/${y}`}
function longDate(v){if(!v)return'';const d=new Date(v+'T12:00:00');return new Intl.DateTimeFormat('es-PE',{day:'2-digit',month:'long',year:'numeric'}).format(d)}
function getRecords(){try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch{return[]}}
function setRecords(v){localStorage.setItem(STORE,JSON.stringify(v))}
function getAudit(){try{return JSON.parse(localStorage.getItem(AUDIT)||'[]')}catch{return[]}}
function log(action,detail){const a=getAudit();a.unshift({id:uid(),at:new Date().toISOString(),action,detail});localStorage.setItem(AUDIT,JSON.stringify(a.slice(0,100)))}
function navigate(view){$$('.view').forEach(x=>x.classList.remove('active'));$('#view-'+view)?.classList.add('active');$$('.nav-item[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#pageTitle').textContent=titles[view]?.[0]||'SIGAD';$('#pageSub').textContent=titles[view]?.[1]||'';$('#sidebar').classList.remove('open');if(view==='dashboard')renderDashboard()}
$$('[data-view]').forEach(x=>x.addEventListener('click',()=>navigate(x.dataset.view)));$$('[data-go]').forEach(x=>x.addEventListener('click',()=>navigate(x.dataset.go)));$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
function depRow(v={}){const tr=document.createElement('tr');tr.innerHTML=`<td class="n"></td><td><input class="dep-name" value="${esc(v.name||'')}" placeholder="Juzgado / dependencia"></td><td><input class="dep-pack" type="number" min="0" value="${num(v.packages)}"></td><td><input class="dep-files" type="number" min="0" value="${num(v.files)}"></td><td><button type="button" class="remove">×</button></td>`;tr.querySelector('.remove').onclick=()=>{tr.remove();reindex();calc()};tr.querySelectorAll('input').forEach(i=>i.addEventListener('input',calc));return tr}
function obsRow(v={}){const tr=document.createElement('tr');tr.innerHTML=`<td class="n"></td><td><input class="obs-dep" value="${esc(v.dep||'')}" placeholder="JIP-01"></td><td><input class="obs-file" value="${esc(v.file||'')}" placeholder="00000-2026-0-..."></td><td><input class="obs-folios" type="number" min="0" value="${num(v.folios)}"></td><td><select class="obs-type">${obsTypes.map(t=>`<option ${t===(v.type||'')?'selected':''}>${t}</option>`).join('')}</select></td><td><input class="obs-text" value="${esc(v.text||'')}" placeholder="Detalle de la observación"></td><td><button type="button" class="remove">×</button></td>`;tr.querySelector('.remove').onclick=()=>{tr.remove();reindex();calc()};return tr}
function packObsRow(v={}){const tr=document.createElement('tr');tr.innerHTML=`<td class="n"></td><td><input class="pobs-dep" value="${esc(v.dep||'')}"></td><td><input class="pobs-code" value="${esc(v.code||'')}"></td><td><input class="pobs-folios" type="number" min="0" value="${num(v.folios)}"></td><td><input class="pobs-text" value="${esc(v.text||'')}"></td><td><button type="button" class="remove">×</button></td>`;tr.querySelector('.remove').onclick=()=>{tr.remove();reindex();calc()};return tr}
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function num(v){return Number(v)||0}
function reindex(){['dependencyRows','observationRows','packageObservationRows'].forEach(id=>$$('#'+id+' tr').forEach((tr,i)=>tr.querySelector('.n').textContent=i+1))}
function calc(){const p=$$('#dependencyRows .dep-pack').reduce((s,x)=>s+num(x.value),0),f=$$('#dependencyRows .dep-files').reduce((s,x)=>s+num(x.value),0),o=$$('#observationRows tr').length,po=$$('#packageObservationRows tr').length;$('#totalPackages').textContent=p;$('#totalFiles').textContent=f;$('#sumPackages').textContent=p;$('#sumFiles').textContent=f;$('#sumObs').textContent=o;$('#sumPackObs').textContent=po}
$('#addDependency').onclick=()=>{$('#dependencyRows').append(depRow());reindex();calc()};$('#addObservation').onclick=()=>{$('#observationRows').append(obsRow());reindex();calc()};$('#addPackageObservation').onclick=()=>{$('#packageObservationRows').append(packObsRow());reindex();calc()};
function collect(){return{id:currentId||uid(),number:$('#officeNumber').value.trim(),date:$('#officeDate').value,recipient:$('#recipient').value.trim(),recipientRole:$('#recipientRole').value.trim(),references:$('#references').value.split('\n').map(x=>x.trim()).filter(Boolean),referenceDate:$('#referenceDate').value,cargoType:$('#cargoType').value,rangeStart:$('#rangeStart').value.trim(),rangeEnd:$('#rangeEnd').value.trim(),dependencies:$$('#dependencyRows tr').map(tr=>({name:tr.querySelector('.dep-name').value.trim(),packages:num(tr.querySelector('.dep-pack').value),files:num(tr.querySelector('.dep-files').value)})).filter(x=>x.name||x.packages||x.files),observations:$$('#observationRows tr').map(tr=>({dep:tr.querySelector('.obs-dep').value.trim(),file:tr.querySelector('.obs-file').value.trim(),folios:num(tr.querySelector('.obs-folios').value),type:tr.querySelector('.obs-type').value,text:tr.querySelector('.obs-text').value.trim()})),packageObservations:$$('#packageObservationRows tr').map(tr=>({dep:tr.querySelector('.pobs-dep').value.trim(),code:tr.querySelector('.pobs-code').value.trim(),folios:num(tr.querySelector('.pobs-folios').value),text:tr.querySelector('.pobs-text').value.trim()})),status:'borrador',updatedAt:new Date().toISOString()}}
function total(r,k){return r.dependencies.reduce((s,x)=>s+num(x[k]),0)}
function save(status='borrador'){const r=collect();if(!r.number){alert('Ingresa el número de oficio.');return null}r.status=status;r.createdAt=r.createdAt||new Date().toISOString();const all=getRecords(),i=all.findIndex(x=>x.id===r.id);if(i>=0){r.createdAt=all[i].createdAt;all[i]=r}else all.unshift(r);setRecords(all);currentId=r.id;log(status==='generado'?'Oficio generado':'Borrador guardado',`${r.number} · ${r.recipient||'Sin destinatario'}`);renderHistory();renderDashboard();return r}
$('#btnSaveDraft').onclick=()=>{const r=save('borrador');if(r)alert('Borrador guardado en este navegador.')};
function newOffice(){currentId=null;$('#officeForm').reset();$('#officeDate').value=isoToday();$('#dependencyRows').innerHTML='';$('#observationRows').innerHTML='';$('#packageObservationRows').innerHTML='';$('#dependencyRows').append(depRow());reindex();calc();$('#historyPanel').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'})}
$('#btnNew').onclick=newOffice;
function dependencyPhrase(r){const names=r.dependencies.map(x=>x.name).filter(Boolean);if(names.length===1)return `correspondientes a ${names[0]}`;if(names.length>1)return `correspondientes a las dependencias detalladas a continuación`;return 'correspondientes a la documentación recepcionada'}
function exhortation(r){const types=[...new Set(r.observations.map(x=>x.type).filter(x=>x&&x!=='OTRO'))];const map={'FALTA RESOLUCIÓN DE ARCHIVO':'falta de resolución de archivo','NO ESTÁ EN LISTADO':'expedientes no consignados en el listado correspondiente','EXPEDIENTE DUPLICADO':'duplicidad de expedientes','RESOLUCIÓN NO CORRESPONDE':'resoluciones que no corresponden al expediente','FALTA TOMO':'falta de tomos','FOLIATURA / TOMOS':'inconsistencias en foliatura o tomos'};const items=types.map(x=>map[x]).filter(Boolean);if(!r.observations.length&&!r.packageObservations.length)return'';const desc=items.length?items.join(', ').replace(/, ([^,]*)$/, ' y $1'):'observaciones en la documentación remitida';return `Por lo tanto, se exhorta a su despacho a disponer que el personal a su cargo verifique de manera previa y rigurosa la documentación remitida al Archivo Desconcentrado, observando estrictamente las disposiciones establecidas. Ello, en razón de haberse advertido ${desc}. Estas situaciones generan devoluciones innecesarias, reprocesos y una mayor carga laboral para esta dependencia. Por lo expuesto, se solicita adoptar las medidas correctivas necesarias a fin de evitar la reiteración de dichas observaciones en futuras remisiones.`}
function previewHtml(r){const tp=total(r,'packages'),tf=total(r,'files'),refs=r.references.map(x=>esc(x)).join('<br>');const depRows=r.dependencies.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name)}</td><td>${x.packages}</td><td>${x.files}</td></tr>`).join('');const obsRows=r.observations.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.dep)}</td><td>${esc(x.file)}</td><td>${x.folios||''}</td><td>${esc(x.text||x.type)}</td></tr>`).join('');const pobRows=r.packageObservations.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.dep)}</td><td>${esc(x.code)}</td><td>${x.folios||''}</td><td>${esc(x.text)}</td></tr>`).join('');const obsIntro=r.observations.length||r.packageObservations.length?`Asimismo, se devuelven <b>${r.observations.length} Expediente(s)</b>${r.packageObservations.length?` y <b>${r.packageObservations.length} Paquete(s)</b>`:''} que se encuentran observados, para lo cual dichas observaciones se detallan a continuación:`:'';return `<div class="doc-head"><h2>CORTE SUPERIOR DE JUSTICIA DEL SANTA</h2><h3>ARCHIVO DESCONCENTRADO</h3></div><p style="text-align:right">Chimbote, ${longDate(r.date)}</p><div class="doc-meta"><div><b>OFICIO N.°:</b> ${esc(r.number)}</div><div><b>Dr.(a):</b> ${esc(r.recipient)}</div><div><b>CARGO:</b> ${esc(r.recipientRole)}</div>${refs?`<div><b>REFERENCIA:</b> ${refs}</div>`:''}${r.referenceDate?`<div><b>FECHA:</b> ${fmtDate(r.referenceDate)}</div>`:''}</div><p>Tengo el agrado de dirigirme a Usted, para saludarlo cordialmente y en atención al documento anotado en la referencia, devolver a su despacho los ${r.cargoType==='digital'?'cargos en digital':'cargos'} de los Expedientes recepcionados por el Archivo Desconcentrado debidamente numerados${r.rangeStart||r.rangeEnd?` del <b>${esc(r.rangeStart)}</b> AL <b>${esc(r.rangeEnd)}</b>`:''} (<b>${tp} PAQUETES</b>), ${dependencyPhrase(r)}, según el siguiente detalle:</p><table><thead><tr><th>ITEM</th><th>JUZGADO / DEPENDENCIA</th><th>CANTIDAD PAQUETES</th><th>CANTIDAD EXPEDIENTES</th></tr></thead><tbody>${depRows}<tr><td colspan="2"><b>TOTAL</b></td><td><b>${tp}</b></td><td><b>${tf}</b></td></tr></tbody></table><p>Para un posterior requerimiento de expedientes al archivo deberá indicar en su Oficio la numeración de paquete asignado en el archivo. ${obsIntro}</p>${r.observations.length?`<table><thead><tr><th>ITEM</th><th>DEPENDENCIA</th><th>NRO EXPEDIENTE</th><th>FOLIOS</th><th>OBSERVACIONES</th></tr></thead><tbody>${obsRows}</tbody></table>`:''}${r.packageObservations.length?`<table><thead><tr><th>ITEM</th><th>DEPENDENCIA</th><th>CÓDIGO DE PAQUETE</th><th>FOLIOS</th><th>OBSERVACIONES</th></tr></thead><tbody>${pobRows}</tbody></table>`:''}${exhortation(r)?`<p>${exhortation(r)}</p>`:''}<p>Es propicia la oportunidad para expresarle mi especial consideración y estima personal.</p><p style="text-align:center"><b><i>Atentamente;</i></b></p><div class="signature"><b>FIRMADO DIGITALMENTE POR:</b><div class="line"></div><b>Responsable<br>Archivo Central de la CSJSA</b></div>`}
function showPreview(){const r=collect();if(!r.number||!r.date||!r.recipient){alert('Completa número, fecha y destinatario.');return}$('#officePreview').innerHTML=previewHtml(r);$('#previewModal').classList.add('open');$('#previewModal').setAttribute('aria-hidden','false')}
$('#btnPreview').onclick=showPreview;$('#closePreview').onclick=()=>$('#previewModal').classList.remove('open');$('#btnPrint').onclick=()=>window.print();$('#btnFinalize').onclick=()=>{const r=save('generado');if(r){$('#officePreview').innerHTML=previewHtml(r);alert('Oficio registrado como generado.')}};
$('#btnDownloadHtml').onclick=()=>{const r=collect();const html=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(r.number)}</title><style>body{font-family:Arial,sans-serif;max-width:850px;margin:40px auto;line-height:1.45}h2,h3{text-align:center}table{width:100%;border-collapse:collapse;font-size:11px;margin:12px 0}th,td{border:1px solid #222;padding:5px}.signature{text-align:center;margin-top:70px}.line{width:260px;border-top:1px solid #111;margin:50px auto 5px}</style></head><body>${previewHtml(r)}</body></html>`;const blob=new Blob([html],{type:'text/html;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Oficio_${r.number.replace(/[^a-z0-9-]/gi,'_')}.html`;a.click();URL.revokeObjectURL(a.href)};
function loadRecord(id){const r=getRecords().find(x=>x.id===id);if(!r)return;currentId=r.id;$('#officeNumber').value=r.number||'';$('#officeDate').value=r.date||'';$('#recipient').value=r.recipient||'';$('#recipientRole').value=r.recipientRole||'';$('#references').value=(r.references||[]).join('\n');$('#referenceDate').value=r.referenceDate||'';$('#cargoType').value=r.cargoType||'digital';$('#rangeStart').value=r.rangeStart||'';$('#rangeEnd').value=r.rangeEnd||'';$('#dependencyRows').innerHTML='';(r.dependencies||[]).forEach(x=>$('#dependencyRows').append(depRow(x)));$('#observationRows').innerHTML='';(r.observations||[]).forEach(x=>$('#observationRows').append(obsRow(x)));$('#packageObservationRows').innerHTML='';(r.packageObservations||[]).forEach(x=>$('#packageObservationRows').append(packObsRow(x)));reindex();calc();$('#historyPanel').classList.add('hidden');navigate('devoluciones');window.scrollTo({top:0,behavior:'smooth'})}
function duplicateRecord(id){const r=getRecords().find(x=>x.id===id);if(!r)return;loadRecord(id);currentId=null;$('#officeNumber').value='';$('#officeDate').value=isoToday();log('Oficio duplicado',r.number);alert('Se copiaron los datos. Asigna el nuevo número de oficio y actualiza el contenido.')}
function deleteRecord(id){if(!confirm('¿Eliminar este registro local?'))return;const all=getRecords(),r=all.find(x=>x.id===id);setRecords(all.filter(x=>x.id!==id));if(r)log('Registro eliminado',r.number);renderHistory();renderDashboard()}
function renderHistory(){const all=getRecords();$('#historyList').innerHTML=all.length?all.map(r=>`<div class="history-row"><strong>${esc(r.number)}</strong><span>${fmtDate(r.date)}</span><span>${esc(r.recipient||'')}</span><span>${total(r,'packages')} paq.</span><span>${r.observations?.length||0} obs.</span><div class="history-actions"><button onclick="loadRecord('${r.id}')">Abrir</button><button onclick="duplicateRecord('${r.id}')">Duplicar</button><button onclick="deleteRecord('${r.id}')">Eliminar</button></div></div>`).join(''):'<p style="color:#667085">Todavía no hay oficios guardados.</p>'}
$('#btnHistory').onclick=()=>{$('#historyPanel').classList.remove('hidden');renderHistory();$('#historyPanel').scrollIntoView({behavior:'smooth'})};$('#closeHistory').onclick=()=>$('#historyPanel').classList.add('hidden');
function renderDashboard(){const rec=getRecords(),generated=rec.filter(x=>x.status==='generado'),pk=generated.reduce((s,r)=>s+total(r,'packages'),0),files=generated.reduce((s,r)=>s+total(r,'files'),0),obs=generated.reduce((s,r)=>s+(r.observations?.length||0),0);$('#stats').innerHTML=[['Oficios generados',generated.length],['Paquetes registrados',pk],['Expedientes registrados',files],['Observaciones',obs]].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1].toLocaleString('es-PE')}</strong></div>`).join('');const mods=[['devoluciones','Devolución de cargos','Generación y trazabilidad de oficios'],['archivo360','Archivo 360','Ubicación visual de paquetes'],['transferencias','Transferencias','Gobierno Regional'],['eliminacion','Eliminación documental','Paquetes y metros lineales'],['reportes','Reportes','PDF / Excel'],['asistente','Asistente','Consultas estructuradas']];$('#moduleGrid').innerHTML=mods.map(m=>`<div class="module-card" onclick="navigate('${m[0]}')"><strong>${m[1]}</strong><span>${m[2]}</span></div>`).join('');const a=getAudit().slice(0,6);$('#recentActivity').innerHTML=a.length?a.map(x=>`<div class="timeline-item"><strong>${esc(x.action)}</strong><span>${esc(x.detail)} · ${new Date(x.at).toLocaleString('es-PE')}</span></div>`).join(''):'<p style="font-size:12px;color:#667085">Sin actividad registrada todavía.</p>'}
newOffice();renderDashboard();
window.loadRecord=loadRecord;window.duplicateRecord=duplicateRecord;window.deleteRecord=deleteRecord;window.navigate=navigate;
