(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const paths={home:'m3 10 9-7 9 7v11h-6v-7H9v7H3z',file:'M6 3h8l5 5v13H6z M14 3v6h5 M9 13h7 M9 17h7',map:'m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2z M9 3v16 M15 5v16',truck:'M2 5h12v12H2z M14 9h4l4 5v3h-8 M6 17a2 2 0 1 0 0 4 2 2 0 0 0 0-4 M18 17a2 2 0 1 0 0 4 2 2 0 0 0 0-4',trash:'M4 6h16 M9 6V3h6v3 M6 6l1 15h10l1-15 M10 10v7 M14 10v7',box:'M3 4h18v5H3z M4 9v12h16V9 M9 13h6 M12 11v5',chart:'M4 20V10 M10 20V4 M16 20v-8 M22 20H2',shield:'m12 3 9 4v6c0 5-9 9-9 9s-9-4-9-9V7z m-5 9 3 3 7-7',bot:'M5 7h14a2 2 0 0 1 2 2v10H3V9a2 2 0 0 1 2-2 M12 3v4 M8 11v3 M16 11v3 M9 17h6 M1 11v5 M23 11v5',settings:'m9 3-1 3-3 1-2 4 2 2-1 3 4 3 3-1 3 2 4-3v-3l3-2-1-5-3-1-1-3z M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M4 22v-3c0-7 16-7 16 0v3',search:'M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0 m-2 5 7 7',sun:'M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M12 1v3 M12 20v3 M1 12h3 M20 12h3 M4 4l2 2 M18 18l2 2 M20 4l-2 2 M6 18l-2 2',bell:'M5 16h14l-2-4V8a5 5 0 0 0-10 0v4z M10 20h4',menu:'M4 6h16 M4 12h16 M4 18h16',send:'m3 3 19 9-19 9 3-9z M6 12h16'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.file}"/></svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const num=v=>Math.max(0,Number(v)||0),fmt=v=>num(v).toLocaleString('es-PE'),sum=(a,k)=>a.reduce((t,x)=>t+num(x[k]),0),total=(r,k)=>sum(r.dependencies||[],k);
const data=()=>SIGAD.getData(),nowYear=()=>String(new Date().getFullYear()),date=v=>v?String(v).split('-').reverse().join('/'):'No registrada';
const completedT=a=>a.filter(x=>['Transferida','Acta registrada','Finalizada'].includes(x.status));
const completedE=a=>a.filter(x=>x.status==='Concluida');
const inYear=(a,y)=>a.filter(x=>String(x.date||'').startsWith(y));
const months=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];
const colors=['#a70038','#0984d7','#1daa57','#ff7d25'];
function hydrate(root=document){$$('[data-icon]',root).forEach(e=>e.innerHTML=icon(e.dataset.icon));$$('[data-go]',root).forEach(b=>b.onclick=()=>SIGAD.navigate(b.dataset.go));}
let year=nowYear();
function renderDashboard(){
const d=data(),years=[...new Set([nowYear(),...d.offices.concat(d.transfers,d.eliminations).map(x=>String(x.date||'').slice(0,4)).filter(x=>/^\d{4}$/.test(x))])].sort().reverse();
$('#dashboardYear').innerHTML=years.map(y=>`<option ${y===year?'selected':''}>${y}</option>`).join('');
const o=inYear(d.offices.filter(x=>x.status==='generado'),year),t=completedT(inYear(d.transfers,year)),e=completedE(inYear(d.eliminations,year));
const cards=[['file','Oficios dev. cargos',fmt(o.length),fmt(o.reduce((s,x)=>s+total(x,'files'),0))+' expedientes','devoluciones'],['truck','Transferencias',fmt(t.length),fmt(sum(t,'packages'))+' paquetes concluidos','transferencias'],['trash','Eliminaciones',fmt(e.length),fmt(sum(e,'packages'))+' paquetes eliminados','eliminacion'],['box','SAAMIR','—','Sin conexión de datos','saamir'],['shield','SAMICERT','—','Sin conexión de datos','samicert']];
$('#stats').innerHTML=cards.map((c,i)=>`<button class="stat metric-card color-${i}" ${i<3?`data-go="${c[4]}"`:`data-external="${c[4]}"`}><span class="metric-icon">${icon(c[0])}</span><span class="metric-copy"><span>${c[1]}</span><strong>${c[2]}</strong><small>${c[3]}</small></span></button>`).join('');
renderMonthly(o,t,e);renderRepository(d.ranges);
const mods=[['devoluciones','file','Devolución de Cargos','Genera oficios de devolución'],['archivo360','map','Archivo 360','Ubica paquetes en repositorios'],['transferencias','truck','Transferencias','Gestión al Gobierno Regional'],['eliminacion','trash','Eliminación Documental','Registros y estadísticas'],['saamir','box','SAAMIR','Abrir sistema externo'],['samicert','shield','SAMICERT','Abrir sistema externo']];
$('#moduleGrid').innerHTML=mods.map((m,i)=>`<button class="module-card color-${i}" ${i<4?`data-go="${m[0]}"`:`data-external="${m[0]}"`}><span class="module-icon">${icon(m[1])}</span><span><strong>${m[2]}</strong><small>${m[3]}</small></span>${i>3?'<b>↗</b>':''}</button>`).join('');
$('#recentActivity').innerHTML=d.audit.length?d.audit.slice(0,5).map(x=>`<button class="timeline-item" data-go="auditoria"><span class="event-icon">${icon(/oficio/i.test(x.action)?'file':/transfer/i.test(x.action)?'truck':/elimina/i.test(x.action)?'trash':'chart')}</span><span><strong>${esc(x.action)}</strong><small>${esc(x.detail)}</small><time>${esc(new Date(x.at).toLocaleString('es-PE',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}))}</time></span><b>›</b></button>`).join(''):'<div class="empty"><span class="empty-symbol">'+icon('chart')+'</span>Tu actividad aparecerá aquí.<small>Registra un oficio para comenzar.</small></div>';
const obs=o.flatMap(x=>x.observations||[]),files=o.reduce((s,r)=>s+total(r,'files'),0),rate=files?obs.length/files*100:0,counts={};obs.forEach(x=>{const k=x.type||'OTRO';counts[k]=(counts[k]||0)+1});const rank=Object.entries(counts).sort((a,b)=>b[1]-a[1]);
$('#observationGauge').innerHTML=`<div class="observation-ring" style="--rate:${Math.min(100,rate)}%"><span><strong>${files?rate.toFixed(2)+' %':'—'}</strong><small>Índice de<br>observación</small></span></div><small>${fmt(obs.length)} observaciones / ${fmt(files)} expedientes</small>`;
$('#obsRanking').innerHTML=rank.length?rank.slice(0,6).map(([k,v],i)=>`<div class="bar-row"><span>${esc(k)}</span><div class="bar-track"><div class="bar-fill" style="width:${v/rank[0][1]*100}%;background:${colors[i%4]}"></div></div><strong>${fmt(v)}</strong></div>`).join(''):'<div class="empty">Sin observaciones registradas en '+year+'.</div>';
hydrate($('#view-dashboard'));$$('[data-external]').forEach(b=>b.onclick=()=>window.open('https://'+b.dataset.external+'.ecomindsetgo.com','_blank','noopener'));
}
function renderMonthly(o,t,e){const metric=$('#chartMetric').value;const values=[o,t,e].map((a,i)=>months.map((_,m)=>a.filter(x=>Number(String(x.date).slice(5,7))===m+1).reduce((s,x)=>s+(metric==='records'?1:i===0?total(x,'packages'):num(x.packages)),0)));const max=Math.max(4,...values.flat()),top=Math.ceil(max/4)*4,W=600,H=210,left=45,plot=540,base=178,height=154;
let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Actividad mensual ${year}, ${metric==='records'?'registros':'paquetes'}"><title>Actividad mensual ${year}</title>`;
for(let i=0;i<=4;i++){const y=base-i*height/4;svg+=`<line x1="${left}" y1="${y}" x2="590" y2="${y}" stroke="var(--line)"/><text x="36" y="${y+4}" text-anchor="end">${fmt(top*i/4)}</text>`}
months.forEach((m,j)=>{const x=left+j*plot/12;svg+=`<text x="${x+20}" y="201" text-anchor="middle">${m}</text>`;values.forEach((v,i)=>{const h=v[j]/top*height;svg+=`<rect x="${x+7+i*10}" y="${base-h}" width="7" height="${h}" rx="2" fill="${colors[i]}"><title>${m}: ${['Devoluciones','Transferencias','Eliminaciones'][i]} ${fmt(v[j])}</title></rect>`})});svg+='</svg>';
$('#monthlyChart').innerHTML=svg+(values.flat().some(Boolean)?'':`<div class="chart-empty">Sin actividad concluida en ${year}</div>`)+`<details class="chart-data"><summary>Ver datos del gráfico</summary><div class="table-wrap"><table><thead><tr><th>Mes</th><th>Devoluciones</th><th>Transferencias</th><th>Eliminaciones</th></tr></thead><tbody>${months.map((m,i)=>`<tr><td>${m}</td>${values.map(v=>`<td>${fmt(v[i])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details>`;
}
function renderRepository(ranges){const repos=['Sáenz Peña','NCPP - Sótano','López Padilla','Dunas'];const vals=repos.map(repo=>{const groups={};ranges.filter(r=>r.repo===repo&&!(repo==='Dunas'&&!r.prefix)).forEach(r=>{(groups[norm(r.prefix)]??=[]).push([num(r.from),num(r.to)])});if(repo==='Dunas'){[['T21',1000],['T22',504],['T23',516],['T24',74]].forEach(([k,v])=>{(groups[k]??=[]).push([1,v])})}return Object.values(groups).reduce((sum,rr)=>{rr.sort((a,b)=>a[0]-b[0]);let end=-1;for(const [a,b]of rr){if(b>=a&&b>end){sum+=b-Math.max(a,end+1)+1;end=b}}return sum},0)});const all=sum(vals.map(v=>({v})),'v');let start=0;const parts=vals.map((v,i)=>{const end=start+(all?v/all*100:0),part=`${colors[i]} ${start}% ${end}%`;start=end;return part});
$('#repositoryChart').innerHTML=`<div class="repo-donut" style="background:conic-gradient(${all?parts.join(','):'var(--line) 0% 100%'})"><span><strong>${fmt(all)}</strong><small>códigos cubiertos</small></span></div><div class="repo-legend">${repos.map((r,i)=>`<button data-repo-link="${esc(r)}"><i style="background:${colors[i]}"></i><span>${r}</span><b>${fmt(vals[i])}<small>${all?Math.round(vals[i]/all*100):0} %</small></b></button>`).join('')}</div>`;
$$('[data-repo-link]').forEach(b=>b.onclick=()=>{SIGAD.navigate('archivo360');SIGAD360.selectRepo(b.dataset.repoLink)});
}
function officeCard(r){return `<article class="office-answer"><h3>${icon('file')} Oficio ${esc(r.number)}</h3><span class="answer-status">${r.status==='generado'?'Generado':'Borrador'}</span><dl><dt>Fecha</dt><dd>${esc(date(r.date))}</dd><dt>Destinatario</dt><dd>${esc(r.recipient||'No registrado')}</dd><dt>Dependencia / módulo</dt><dd>${esc(r.recipientRole||'No registrado')}</dd><dt>Referencia</dt><dd>${(r.references||[]).map(esc).join('<br>')||'Sin referencias'}</dd><dt>Rango de paquetes</dt><dd>${esc(r.rangeStart||'—')} al ${esc(r.rangeEnd||'—')}</dd><dt>Total de paquetes</dt><dd>${fmt(total(r,'packages'))}</dd><dt>Total de expedientes</dt><dd>${fmt(total(r,'files'))}</dd></dl><h4>Dependencias</h4><ul>${(r.dependencies||[]).map(x=>`<li>${esc(x.name)}: <b>${fmt(x.packages)} paq.</b> · ${fmt(x.files)} exp.</li>`).join('')||'<li>No registradas</li>'}</ul><dl><dt>Expedientes observados</dt><dd>${r.observations?.length||0}</dd><dt>Paquetes observados</dt><dd>${r.packageObservations?.length||0}</dd></dl><button class="secondary small" data-office-open="${esc(r.id)}">${icon('search')} Ver oficio completo</button></article>`}
let lastOffice=null;
function period(q){const s=norm(q),ym=s.match(/\b(20\d{2})\b/),names=['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'];let y=ym?.[1]||null,m=names.findIndex(x=>s.includes(x));if(s.includes('este ano')||s.includes('este mes'))y=nowYear();if(s.includes('este mes'))m=new Date().getMonth();if(m>=0&&!y)y=year;return {y,m,label:[m>=0?names[m]:'',y||'todos los periodos'].filter(Boolean).join(' '),filter:a=>a.filter(x=>(!y||String(x.date||'').startsWith(y))&&(m<0||Number(String(x.date||'').slice(5,7))===m+1))}}
function answer(q){const d=data(),s=norm(q),p=period(q);const numbered=s.match(/\boficios?\s*(?:n(?:ro|umero)?\.?\s*[°ºo.]?\s*)?(\d{1,6})(?!\d)/);const pkg=q.match(/\b\d{1,4}-\d{2}T\b|\b\d+R\b|\b\d{2}-\d+[A-Za-z]*\b/i)?.[0];
if(numbered){const id=Number(numbered[1]),list=d.offices.filter(x=>Number(String(x.number||'').match(/\d+/)?.[0])===id&&(!p.y||String(x.date||'').startsWith(p.y)));if(!list.length){lastOffice=null;return `No encontré el Oficio ${esc(numbered[1])}${p.y?' del año '+p.y:''}. Revisa el historial o restaura el respaldo que lo contiene.`}lastOffice=list.length===1?list[0].id:null;return (list.length>1?'<p>Hay varias coincidencias. Indica el año o revisa el documento correspondiente.</p>':'')+list.map(officeCard).join('')}
if(lastOffice&&/^(y |sus |cuales son sus|que dependencias|de que modulo|a que modulo)/.test(s)){const r=d.offices.find(x=>x.id===lastOffice);if(r)return officeCard(r)}
if((s.includes('donde')||s.includes('ubic')||s.includes('busca'))&&pkg){const info=window.SIGAD360?.findPackageInfo(pkg),matches=SIGAD.findPackage(pkg);const found=info?.found||matches.length;return found?`<p>El paquete <b>${esc(pkg)}</b> corresponde a ${esc(info?.found?info.text:matches.map(x=>`${x.repo}, sector ${x.sector||'por definir'}, estantería ${x.shelf||'por definir'}, nivel ${x.level||'por definir'}`).join('; '))}.</p><button class="secondary small" data-package="${esc(pkg)}">Ver ubicación en Archivo 360</button>`:`No encontré el paquete ${esc(pkg)} en los rangos configurados.`}
const o=p.filter(d.offices.filter(x=>x.status==='generado')),t=p.filter(d.transfers),e=p.filter(d.eliminations),tc=completedT(t),ec=completedE(e);
const scope=`<small class="answer-scope">Periodo: ${esc(p.label)} · Fuente: registros locales</small>`;
if(s.includes('resumen'))return scope+`<b>Resumen de gestión</b><ul><li>${fmt(o.length)} oficios generados: ${fmt(o.reduce((v,r)=>v+total(r,'packages'),0))} paquetes y ${fmt(o.reduce((v,r)=>v+total(r,'files'),0))} expedientes.</li><li>${fmt(tc.length)} transferencias concluidas: ${fmt(sum(tc,'packages'))} paquetes; ${t.length-tc.length} pendientes.</li><li>${fmt(ec.length)} eliminaciones concluidas: ${fmt(sum(ec,'packages'))} paquetes; ${fmt(sum(ec,'meters'))} metros lineales liberados; ${e.length-ec.length} pendientes.</li></ul>`;
if(s.includes('saamir')||s.includes('samicert'))return 'SAAMIR y SAMICERT están disponibles mediante sus accesos externos. SIGAD todavía no tiene conexión con sus datos y no puede consultar sus totales.';
if(s.includes('oficio')){const known=[...new Set(d.offices.flatMap(x=>[x.recipientRole,...(x.dependencies||[]).map(z=>z.name)]).filter(Boolean))],dep=known.find(x=>s.includes(norm(x))),list=dep?o.filter(x=>norm(x.recipientRole)===norm(dep)||(x.dependencies||[]).some(z=>norm(z.name)===norm(dep))):o;if(/dependencia|modulo|juzgado/.test(s)&&!dep)return 'Indica el número del oficio (por ejemplo, «¿De qué dependencia es el Oficio 001?») o escribe el nombre completo de la dependencia registrada.';return scope+`Hay <b>${fmt(list.length)} oficios generados</b>${dep?' vinculados a '+esc(dep):''}, con ${fmt(list.reduce((v,r)=>v+total(r,'packages'),0))} paquetes y ${fmt(list.reduce((v,r)=>v+total(r,'files'),0))} expedientes.`+(list.length?'<div class="answer-links">'+list.slice(0,12).map(r=>`<button data-office-answer="${esc(r.id)}">Oficio ${esc(r.number)} · ${esc(r.recipientRole||'Sin dependencia')}</button>`).join('')+'</div>':'')}
if(s.includes('observ')){const obs=o.flatMap(x=>x.observations||[]),causes={};obs.forEach(x=>causes[x.type||'OTRO']=(causes[x.type||'OTRO']||0)+1);return scope+`<b>${fmt(obs.length)} expedientes observados</b>.<ul>${Object.entries(causes).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<li>${esc(k)}: ${fmt(v)}</li>`).join('')}</ul>`}
if(s.includes('transfer'))return scope+`Hay ${fmt(t.length)} transferencias registradas. <b>${fmt(tc.length)} concluidas</b>, con ${fmt(sum(tc,'packages'))} paquetes y ${fmt(sum(tc,'meters'))} metros lineales. Pendientes: ${t.length-tc.length}.`+(t.length?`<ul>${t.map(x=>`<li>${esc(date(x.date))} · ${esc(x.destination)} · ${fmt(x.packages)} paq. · ${esc(x.status)}</li>`).join('')}</ul>`:'');
if(s.includes('elimin')||s.includes('metros'))return scope+`Hay ${fmt(e.length)} procesos registrados. <b>${fmt(ec.length)} concluidos</b>, con ${fmt(sum(ec,'packages'))} paquetes y ${fmt(sum(ec,'meters'))} metros lineales liberados. Pendientes: ${e.length-ec.length}.`+(e.length?`<ul>${e.map(x=>`<li>${esc(date(x.date))} · ${esc(x.repos)} · ${fmt(x.packages)} paq. · ${esc(x.status)}</li>`).join('')}</ul>`:'');
if(s.includes('paquete')||s.includes('expediente'))return scope+`Los oficios generados contienen ${fmt(o.reduce((v,r)=>v+total(r,'packages'),0))} paquetes y ${fmt(o.reduce((v,r)=>v+total(r,'files'),0))} expedientes. Transferencias concluidas: ${fmt(sum(tc,'packages'))} paquetes. Eliminaciones concluidas: ${fmt(sum(ec,'packages'))} paquetes. Estos totales corresponden a procesos distintos y no deben sumarse como inventario único.`;
return 'Puedo consultar oficios por número, dependencias, paquetes, observaciones, transferencias y eliminaciones. Prueba «Oficio 010», «Resumen de septiembre de 2026» o «¿Dónde está el paquete 14572R?». Si necesitas otro dato, indica el módulo y el periodo.';
}
function bindAnswers(){const host=$('#assistantMessages');$$('[data-office-open]',host).forEach(b=>b.onclick=()=>SIGAD.viewOffice(b.dataset.officeOpen));$$('[data-office-answer]',host).forEach(b=>b.onclick=()=>{const r=data().offices.find(x=>x.id===b.dataset.officeAnswer);if(r){lastOffice=r.id;appendBot(officeCard(r))}});$$('[data-package]',host).forEach(b=>b.onclick=()=>{SIGAD.navigate('archivo360');$('#packageSearch').value=b.dataset.package;SIGAD360.search(b.dataset.package);if(innerWidth<1400)closeAssistant()});$$('[data-ask]',host).forEach(b=>b.onclick=()=>send(b.textContent));}
function appendBot(html){const host=$('#assistantMessages');host.insertAdjacentHTML('beforeend',`<div class="chat-line bot-line"><span class="chat-avatar">${icon('bot')}</span><div class="msg bot">${html}</div></div>`);bindAnswers();host.scrollTop=host.scrollHeight;}
function send(q){q=String(q??$('#assistantQuery').value).trim().slice(0,1000);if(!q)return;$('#assistantMessages').insertAdjacentHTML('beforeend',`<div class="chat-line user-line"><div class="msg user">${esc(q)}</div><span class="chat-avatar">${icon('user')}</span></div>`);$('#assistantQuery').value='';appendBot(answer(q));SIGAD.log('Consulta al asistente',q);renderDashboard();}
function openAssistant(){document.body.classList.add('assistant-open');document.body.classList.remove('assistant-collapsed');$('#assistantQuery').focus()}
function closeAssistant(){document.body.classList.remove('assistant-open');document.body.classList.add('assistant-collapsed');$('#openAssistant').focus()}
function search(){const q=$('#globalSearch').value.trim(),s=norm(q),d=data();const mods=[['dashboard','Dashboard'],['devoluciones','Devolución de Cargos'],['archivo360','Archivo 360'],['transferencias','Transferencias'],['eliminacion','Eliminación Documental'],['reportes','Reportes'],['auditoria','Auditoría'],['configuracion','Configuración']];let html=mods.filter(x=>!s||norm(x[1]).includes(s)).map(x=>`<button data-search-view="${x[0]}">${icon('box')}<span><strong>${x[1]}</strong><small>Módulo SIGAD</small></span>›</button>`).join('');if(s){html+=d.offices.filter(x=>norm([x.number,x.recipient,x.recipientRole,...(x.dependencies||[]).map(z=>z.name)].join(' ')).includes(s)).slice(0,20).map(x=>`<button data-search-office="${esc(x.id)}">${icon('file')}<span><strong>Oficio ${esc(x.number)}</strong><small>${esc(x.recipientRole)} · ${esc(x.status)}</small></span>›</button>`).join('');html+=`<button id="searchAsk">${icon('bot')}<span>Consultar al asistente: <b>${esc(q)}</b></span>›</button>`}$('#searchResults').innerHTML=html;$$('[data-search-view]').forEach(b=>b.onclick=()=>{$('#searchDialog').close();SIGAD.navigate(b.dataset.searchView)});$$('[data-search-office]').forEach(b=>b.onclick=()=>{$('#searchDialog').close();SIGAD.viewOffice(b.dataset.searchOffice)});$('#searchAsk')?.addEventListener('click',()=>{$('#searchDialog').close();openAssistant();send(q)});}
function openSearch(){$('#searchDialog').showModal();$('#globalSearch').value='';search();$('#globalSearch').focus()}
function profile(){let name='Alfredo Cruzado';try{name=localStorage.getItem('sigad_profile_name')||name}catch{}$$('.profile-name').forEach(e=>e.textContent=name);$('#welcomeName').textContent=name.trim().split(/\s+/)[0];$('#profileName').value=name;}
window.SIGADUI={renderDashboard,openAssistant,answer};
hydrate();profile();renderDashboard();
appendBot(`<strong>Hola, soy el Asistente SIGAD 👋</strong><p>Puedo ayudarte a consultar la información registrada en los módulos del sistema. Prueba con estas preguntas:</p><div class="suggestions">${['¿Cuántos oficios se generaron en '+nowYear()+'?','¿De qué dependencia es el Oficio 001?','¿Cuántos paquetes se transfirieron?','¿Dónde está el paquete 14572R?','¿Qué eliminaciones se realizaron?','Genera un resumen de septiembre.'].map(q=>`<button data-ask>${esc(q)}</button>`).join('')}</div>`);
$('#assistantForm').onsubmit=e=>{e.preventDefault();send()};$('#closeAssistant').onclick=closeAssistant;$('#openAssistant').onclick=openAssistant;$('#assistantBackdrop').onclick=closeAssistant;
$('#dashboardYear').onchange=e=>{year=e.target.value;renderDashboard()};$('#chartMetric').onchange=renderDashboard;
$('#searchTrigger').onclick=openSearch;$('#closeSearch').onclick=()=>$('#searchDialog').close();$('#globalSearch').oninput=search;
$('#searchDialog').onclick=e=>{if(e.target===$('#searchDialog'))$('#searchDialog').close()};
$('#brandHome').onclick=e=>{e.preventDefault();SIGAD.navigate('dashboard')};
$('#notificationToggle').onclick=()=>SIGAD.navigate('auditoria');$('#settingsBackup').onclick=()=>$('#btnBackup').click();
$('#profileForm').onsubmit=e=>{e.preventDefault();const name=$('#profileName').value.trim();if(!name)return;try{localStorage.setItem('sigad_profile_name',name);profile();SIGAD.toast('Nombre actualizado.','success')}catch{SIGAD.toast('No se pudo guardar el nombre.','error')}};
try{document.body.classList.toggle('dark-theme',localStorage.getItem('sigad_theme')==='dark')}catch{}
$('#themeToggle').onclick=()=>{const dark=document.body.classList.toggle('dark-theme');$('#themeToggle').setAttribute('aria-pressed',String(dark));try{localStorage.setItem('sigad_theme',dark?'dark':'light')}catch{}};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape'&&document.body.classList.contains('assistant-open'))closeAssistant()});
window.addEventListener('storage',renderDashboard);
})();
